//4DPlugin.h
/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : new Project
 #	author : phimage
 #	07/06/2026
 #
 # --------------------------------------------------------------------------------*/






// --- Swift
void Swift_Greeting( PA_PluginParameters params );
