//4DPlugin.cpp
/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : new Project
 #	author : phimage
 #	07/06/2026
 #
 # --------------------------------------------------------------------------------*/




#include "4DPluginAPI.h"
#include "4DPlugin.h"
#include "SwiftBridge.h"

#include <CoreFoundation/CoreFoundation.h>
#include <string>
#include <vector>
#include <cstdlib>

#pragma mark - string helpers

// Convert the 4D text parameter (UTF-16) at `index` to a UTF-8 std::string.
static std::string GetUTF8Parameter( PA_PluginParameters params, short index )
{
	PA_Unistring* ustr = PA_GetStringParameter( params, index );
	if( ustr == nullptr )
		return std::string();

	PA_Unichar* chars = PA_GetUnistring( ustr );
	PA_long32 length = PA_GetUnistringLength( ustr );
	if( chars == nullptr || length <= 0 )
		return std::string();

	CFStringRef cf = CFStringCreateWithCharacters( kCFAllocatorDefault,
	                                               reinterpret_cast<const UniChar*>( chars ),
	                                               length );
	if( cf == nullptr )
		return std::string();

	CFIndex maxSize = CFStringGetMaximumSizeForEncoding( CFStringGetLength( cf ),
	                                                     kCFStringEncodingUTF8 ) + 1;
	std::vector<char> buffer( maxSize, 0 );
	std::string result;
	if( CFStringGetCString( cf, buffer.data(), maxSize, kCFStringEncodingUTF8 ) )
		result.assign( buffer.data() );

	CFRelease( cf );
	return result;
}

// Return a UTF-8 C string to 4D as a text result (converted back to UTF-16).
static void ReturnUTF8( PA_PluginParameters params, const char* utf8 )
{
	if( utf8 == nullptr )
		utf8 = "";

	CFStringRef cf = CFStringCreateWithCString( kCFAllocatorDefault, utf8, kCFStringEncodingUTF8 );
	if( cf == nullptr )
		return;

	CFIndex length = CFStringGetLength( cf );
	std::vector<UniChar> buffer( length + 1, 0 );
	CFStringGetCharacters( cf, CFRangeMake( 0, length ), buffer.data() );
	buffer[length] = 0; // PA_ReturnString expects a NUL-terminated PA_Unichar*

	PA_ReturnString( params, reinterpret_cast<PA_Unichar*>( buffer.data() ) );
	CFRelease( cf );
}

#pragma mark -

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- Swift
		case 1 :
			Swift_Greeting( params );
			break;

	}
}
 

// ------------------------------------- Swift ------------------------------------
// Calls into Swift code. Syntax: Swift_Greeting(&T):T
void Swift_Greeting( PA_PluginParameters params )
{
	std::string name = GetUTF8Parameter( params, 1 );

	char* greeting = swift_greeting( name.c_str() ); // implemented in PluginSwift.swift
	ReturnUTF8( params, greeting );
	free( greeting );                                // release Swift's strdup() result
}
 
